### ISSUE TITLE
Excellent 

### ISSUE THREAD

**Issue by lockhartsoftware** [CodeFontana/BlazorAzureAuthDemo#1]
This is excellent. Thanks. Have you figured out how to securely call a .NET 8.0 Web API from the WebApp?

**Comment by CodeFontana** [comment]
@lockhartsoftware as this is a Blazor server-side project, I would typically bypass an API and use a library project to communicate directly with the database.

My general strategy is typically:
- Server-side projects can communicate directly with the database.
- Client-side projects should only communicate with a Web API.

If you refer to either of these projects, they have a Blazor WebAssembly app communicating with an API for authentication and for general data access:
https://github.com/CodeFontana/CSharpProjectTemplates [MudBlazorWasmUI + WebApi projects]
https://github.com/CodeFontana/DatingApp

However, in both aforementioned projects, the API is using in-app authentication based on EF Core with the database.  They are not using Organizational Auth, e.g. Azure OpenID Connect.

I suspect you're looking for a project where both the Web API and Web App are using OpenID connect?

If so, I'm afraid I don't yet have a sample for this.  It is on my mind, and something I will create a separate repository for.

Some approaches off the top of my head:
1- Blazor Web App integrated with Entra OIDC same as this sample.  Except overriding the AuthStateProvider with a custom one, so the OpenID connect token can be captured into the user's state.  That token could then be added as a header in the HttpClient used to communicate with the API, and up to the API project to also integrate/validate the token with Azure.

2- API might have its own auth, in-app or organizational, not necessarily the same as the Web App.  The Web App would integrate with Entra OIDC, same as this repo.  In your library or service code for interacting with the API, you would hit the APIs respective auth endpoint to obtain a token, again, whether that API is using in-app, organization, or maybe even simply an API key.

Feel free to checkout this project for demo of various API authentication scenarios:
https://github.com/CodeFontana/ApiAuthDemos

**Comment by lockhartsoftware** [comment]
Thank you, Brian, for your detailed and informative response.

I think we have both been thinking along the same lines, but you have done so much more, practically, in terms of code, implementation, etc.

Yes, I am looking for a project where both the Web API and Web App are using OpenID connect. I hope you get an opportunity to create something. If I come across something like that I will share with you.

I really like both of your 'off the top of my head' approaches - I will give them some thought.

Wow! I've just been looking at your 'ApiAuthDemos' demos. Thanks, this is so informative.

Thanks again.
